Repository cased/shell, pull requests merged in 2023-02, with the labels that each got.

#5 Fix terminal exit command
  apps/shell/src/app/modules/prompt/prompt.spec.tsx
  apps/shell/src/app/modules/prompt/prompt.tsx
Labels: Front End

#12 Fixed a bug where success notifications printed red
  apps/shell/src/app/modules/notification-list/notification-list.tsx
Labels: Front End

#14 Publish Helm chart to ghcr.io/cased/cased-shell
  .devcontainer/Dockerfile
  .github/workflows/charts-test.yml
  .github/workflows/charts.yml
  .github/workflows/required.js
  .github/workflows/required.yml
  charts/README.md
  charts/cased-shell/Chart.yaml
Labels: helm:push

#18 Fallback to index.html with try_files
  Caddyfile
  charts/cased-shell/Chart.yaml
  charts/cased-shell/README.md
  charts/cased-shell/README.md.gotmpl
  tests/integration/test-self-signed-tls.sh
Labels: docker:pr-image

#19 Ash/cas 418 user or group log should show emailname
  README.md
  apps/shell/src/app/modules/settings/pages/settings-approvals/form-partial-approval-privilege/form-partial-approval-privilege.spec.tsx
  apps/shell/src/app/modules/settings/pages/settings-approvals/form-partial-approval-privilege/form-partial-approval-privilege.tsx
  apps/shell/src/app/modules/settings/pages/settings-approvals/sub-pages/edit-access-approval/edit-access-approval.tsx
  apps/shell/src/app/modules/settings/pages/settings-approvals/sub-pages/edit-program-approval/edit-program-approval.spec.tsx
  apps/shell/src/app/modules/settings/pages/settings-approvals/sub-pages/edit-program-approval/edit-program-approval.tsx
  apps/shell/src/app/modules/settings/pages/settings-runbooks/databases/create-database/create-database.tsx
  apps/shell/src/app/modules/settings/pages/settings-runbooks/databases/database-form/database-form.tsx
  apps/shell/src/app/modules/settings/pages/settings-runbooks/databases/edit-database/edit-database.tsx
  apps/shell/src/app/modules/settings/pages/settings-runbooks/providers/create-provider/create-provider.tsx
  apps/shell/src/app/modules/settings/pages/settings-runbooks/providers/edit-provider/edit-provider.tsx
  apps/shell/src/app/modules/settings/pages/settings-runbooks/providers/provider-form/provider-form.tsx
  apps/shell/src/app/modules/settings/pages/settings-runbooks/settings-runbooks.spec.tsx
  apps/shell/src/app/modules/settings/pages/settings-user-profile/settings-user-profile.tsx
  apps/shell/src/app/modules/settings/pages/settings-users/settings-users.tsx
  apps/shell/src/app/modules/settings/pages/settings-users/sub-pages/group-logs/group-logs.spec.tsx
  apps/shell/src/app/modules/settings/pages/settings-users/sub-pages/group-logs/group-logs.tsx
  apps/shell/src/app/modules/settings/pages/settings-users/sub-pages/user-logs/user-logs.spec.tsx
  apps/shell/src/app/modules/settings/pages/settings-users/sub-pages/user-logs/user-logs.tsx
  apps/shell/src/app/modules/settings/pages/settings-users/tables/table-groups/table-groups.tsx
  apps/shell/src/app/modules/settings/pages/settings-users/tables/table-users-and-roles/table-users-and-roles.tsx
  libs/data/src/lib/data.ts
  libs/data/src/lib/i-api-provider.ts
  libs/data/src/lib/i-entry.ts
  libs/data/src/lib/i-settings-approvals.ts
  libs/data/src/lib/i-settings.ts
  libs/data/src/lib/i-user.ts
  libs/redux/src/lib/stores/activities/activities.store.ts
  libs/redux/src/lib/stores/auth/auth.store.ts
  libs/redux/src/lib/stores/settings/i-settings-approvals.store.ts
  libs/redux/src/lib/stores/settings/i-settings-store.ts
  libs/redux/src/lib/stores/settings/settings-runbooks.store.ts
  libs/redux/src/lib/stores/settings/settings.store.ts
  libs/redux/src/lib/stores/settings/settings.thunks.ts
  libs/remotes/src/lib/activities/activities-service.ts
  libs/remotes/src/lib/remotes.tsx
  libs/remotes/src/lib/settings/approvals/settings-approvals.service.ts
  libs/remotes/src/lib/settings/i-settings-api-response.ts
  libs/remotes/src/lib/settings/i-settings.ts
  libs/remotes/src/lib/settings/runbooks/settings-runbooks.service.spec.ts
  libs/remotes/src/lib/settings/runbooks/settings-runbooks.service.ts
  libs/remotes/src/lib/settings/settings-service.spec.ts
  libs/remotes/src/lib/settings/settings-service.ts
  libs/remotes/src/lib/settings/settings-service.utilities.ts
  libs/remotes/src/lib/users/users.service.ts
  libs/remotes/tsconfig.lib.json
  libs/test-utilities/src/lib/builders/api-provider.builder.ts
  libs/test-utilities/src/lib/builders/approval-program.builder.ts
  libs/test-utilities/src/lib/builders/runbook-database.builder.ts
  libs/test-utilities/src/lib/builders/settings-response.builder.ts
  libs/test-utilities/src/lib/builders/user.builder.ts
  shell/controllers/v2/api/session_logs_controller.py
Labels: Front End

#20 Converts the log page back button to a text link
  apps/shell/src/app/modules/settings/settings-template.tsx
  libs/ui/src/lib/text/text-link/text-link.tsx
Labels: Front End

#28 Refactored prompt search to open and toggle closed properly
  apps/shell/src/app/modules/prompt/prompt-search.tsx
  apps/shell/src/app/modules/prompt/prompt-watcher.tsx
  apps/shell/src/app/modules/prompt/prompt.tsx
  apps/shell/src/app/modules/prompt/search/prompt-search.spec.tsx
  apps/shell/src/app/modules/prompt/search/prompt-search.tsx
  libs/redux/src/lib/utils/factory.tsx
Labels: Front End

#27 [Helm] Fix connecting to demo prompt
  .devcontainer/helm/alb-example.yaml
  .devcontainer/helm/aws-example.yaml
  .devcontainer/helm/shell-dev.yaml
  .devcontainer/script/charts-install
  .devcontainer/script/charts-port-forward
  Caddyfile
  apps/shell/src/app/modules/prompt/prompt.tsx
  charts/cased-shell/Chart.yaml
  charts/cased-shell/INSTALL.md
  charts/cased-shell/README.md
  charts/cased-shell/sshd.sh
  charts/cased-shell/templates/configmap.yaml
  charts/cased-shell/templates/deployment.yaml
  charts/cased-shell/templates/sshd-deployment.yaml
  charts/cased-shell/values.yaml
  libs/redux/src/lib/stores/prompt/prompt.store.ts
  libs/remotes/src/lib/axios.ts
  libs/remotes/src/lib/prompt/prompt-service.ts
  shell/main.py
  tests/integration/test-startup.sh
Labels: docker:pr-image

#45 Runbook exit button
  apps/shell/src/app/modules/runbooks/runbooks.tsx
  apps/shell/src/app/modules/shared/page-two-column/page-two-column.tsx
  libs/ui/jest.config.ts
  libs/ui/src/index.ts
  libs/ui/src/lib/header/header.spec.tsx
  libs/ui/src/lib/header/header.stories.tsx
  libs/ui/src/lib/header/header.tsx
  libs/ui/src/lib/logo/logo.spec.tsx
  libs/ui/src/lib/logo/logo.stories.tsx
  libs/ui/src/lib/logo/logo.tsx
  libs/ui/src/lib/logo/shell-logo.svg
  libs/ui/src/lib/template-two-column/template-two-column.spec.tsx
  libs/ui/src/lib/template-two-column/template-two-column.stories.tsx
  libs/ui/src/lib/template-two-column/template-two-column.tsx
  libs/ui/src/lib/text/text-link/text-link.spec.tsx
Labels: Front End

#49 Added docs on how to use NX's migrate for upgrades
  README-frontend.md
Labels: Front End

#46 Approvals now list as links instead of having to find the details link
  apps/shell/src/app/modules/approvals/approval-card-block-collection.tsx
  apps/shell/src/app/modules/approvals/approval-collection.tsx
  apps/shell/src/app/modules/approvals/approvals-block.spec.tsx
  apps/shell/src/app/modules/approvals/approvals-block.tsx
  apps/shell/src/app/modules/approvals/show/show-approval.tsx
  libs/ui/src/lib/approval/approval.tsx
  libs/ui/src/lib/card/card.tsx
Labels: Front End

#41 add padding for runbook nodes
  apps/shell/src/app/modules/runbooks/action-node/action-node.scss
Labels: Front End

#50 Rest node creation now has properly spacing between inputs
  apps/shell/src/app/modules/runbooks/forms/form-node-rest/form-node-rest.tsx
Labels: Front End

#51 Moved approval status onto a separate line
  libs/ui/src/lib/approval/approval.tsx
Labels: Front End

#52 Ash/cas 441 json format the prompt display on
  apps/shell/src/app/modules/approvals/show/show-approval.tsx
  apps/shell/src/app/modules/login/login.tsx
Labels: Front End

#47 Handle error on connecting/disconnecting
  apps/shell/src/app/modules/prompt/prompt.spec.tsx
  apps/shell/src/app/modules/prompt/prompt.tsx
  apps/shell/src/app/modules/runbooks/forms/form-node-form/form-node-form.tsx
  libs/redux/src/lib/stores/prompt/prompt.store.ts
  libs/remotes/src/lib/prompt/prompt-service.ts
  shell/controllers/v2/api/prompt_sessions_controller.py
Labels: Front End

#63 Terminal Scroll Bug Fix
  apps/shell/src/app/modules/home/home.tsx
  apps/shell/src/app/modules/runbooks/runbooks.tsx
  apps/shell/src/app/modules/settings/pages/settings-users/log-card/log-card.tsx
  libs/redux/src/lib/stores/runbooks/i-runbook-store.ts
  libs/redux/src/lib/stores/runbooks/runbooks.thunks.ts
  libs/test-utilities/src/lib/react-flow-mocks.ts
  package.json
  yarn.lock
Labels: Front End

#72 Re-usable <Form> component with hooks
  apps/shell/src/app/modules/notification-list/notification-list.tsx
  apps/shell/src/app/modules/settings/pages/page-settings-user-manager/page-settings-add-user.tsx
  libs/ui/.storybook/preview.js
  libs/ui/src/index.ts
  libs/ui/src/lib/form/form.spec.tsx
  libs/ui/src/lib/form/form.stories.tsx
  libs/ui/src/lib/form/form.tsx
  libs/ui/src/lib/form/index.tsx
  libs/ui/src/lib/form/use-form-data.tsx
Labels: Front End
